services:
#https://hub.docker.com/r/airensoft/ovenmediaengine/tags
  ovenmediaengine:
    container_name: ovenmediaengine
    image: airensoft/ovenmediaengine:0.18.0
    ports:
      - "1935:1935/tcp"
      - "3333:3333/tcp"
      - "3478:3478/tcp"
      - "4000:4000/udp"
      - "8081:8081/tcp"
      - "9000:9000"
      - "9999:9999/udp"
      - "10000-10005:10000-10005/udp"
    environment:
      - TGRGBOX_HOST=${TGRGBOX_HOST}
      - TGRGBOX_WEB_API_KEY=${TGRGBOX_WEB_API_KEY}
      #If your host is not on the public internet, you need to manually set the IP address for the host.  OME doesn't
      #derive this correctly (it will find your real public IP address presumably using STUN).
      - WHIP_IP_ADDRESS=${WHIP_IP_ADDRESS:-}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./ome-conf:/opt/ovenmediaengine/bin/origin_conf
    restart: unless-stopped
    command: /opt/ovenmediaengine/bin/OvenMediaEngine -c /opt/ovenmediaengine/bin/origin_conf
    labels:
      - "traefik.enable=true"
        #This sort of sucks.  The hls playlist doesn't know about the prefix, so the application prefix has
        #to be in this rule
      - "traefik.http.routers.ome-wss-rtr.rule=Host(`$TGRGBOX_HOST`) && (PathPrefix(`/ome-wss`) || PathPrefix(`/ome-hls`) || PathPrefix(`/tgrgbace`))"
      - "traefik.http.middlewares.ome-strip.stripprefix.prefixes=/ome-wss,/ome-hls"
      - "traefik.http.routers.ome-wss-rtr.middlewares=ome-strip@docker"
      - "traefik.http.routers.ome-wss-rtr.tls=true"
      - "traefik.http.routers.ome-wss-rtr.tls.certresolver=tgrgboxresolver"
      - "traefik.http.services.ome-wss-rtr.loadbalancer.server.port=3333"
    networks:
      - tgrgbox-network

  traefik:
    image: traefik:v3.4.0
    container_name: traefik
    restart: unless-stopped
    profiles: ["reverse-proxy"]
    ports:
      - 80:80
      - 443:443
        #- 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/acme/acme.json
    labels:
      - "traefik.enable=true"
    networks:
      - tgrgbox-network

networks:
  tgrgbox-network:
    external: true

